GET http://localhost:300/

###

POST http://localhost:300/register
Content-Type: application/json

{
    "username": "mirul",
    "password": "1234",
    "name": "Amirul",
    "email": "mirul@gmail.com"
}

###
POST http://localhost:300/
Content-Type: application/json

{
    "username": "ali",
    "password": "password"
}
